name: sosebee
recipe: drupal9
config:
  php: '8.2'
  webroot: web

# Services
services:
  database:
    portforward: 57947
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
  sosebee-phpmyadmin:
    type: phpmyadmin

# Proxy
proxy:
  sosebee-phpmyadmin:
    - sosebee-phpmyadmin.lndo.site

